### ISSUE TITLE
Dropping the server initial packet causes 600ms delay

### ISSUE THREAD

**Issue by janaiyengar** [h2o/quicly#110]
When the server's Initial packet is sent and dropped, connection takes  ~600ms to get set up. This is in part because of #98, and in part because while initial and handshake packets are sent together first, the retransmission carries only the initial packet.

The fix is here https://quicwg.org/base-drafts/draft-ietf-quic-recovery.html#rfc.section.6.2: retransmit as much unacked Initial and Handshake data on a crypto retransmission timeout that can be sent (3 x received packet size, per https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#rfc.section.8.1).

**Comment by kazuho** [comment]
Maybe fix this along with #111.

**Comment by janaiyengar** [comment]
I've verified that this is now fixed (in #111).
