### ISSUE TITLE
Priority between new data and retransmissions

### ISSUE THREAD

**Issue by janaiyengar** [h2o/quicly#133]
Now that we have a stream scheduler, we should ensure that we use the right priorities for old vs. new data. My inclination is to always prioritize per stream priorities, and not care about old or new data.

**Comment by kazuho** [comment]
> My inclination is to always prioritize per stream priorities, and not care about old or new data.

Agreed. That's the abstraction we have. Quicly calls the scheduler whenever there's some room in send window (to determine which stream to send).

**Comment by janaiyengar** [comment]
So we can close this issue, right?
