### ISSUE TITLE
Send at least one retransmission when time-based loss detection happens

### ISSUE THREAD

**Issue by janaiyengar** [h2o/quicly#139]
Currently the sender waits until cwnd space becomes available to rtx, causing recovery delay. Allow one to be sent immediately.

**Comment by kazuho** [comment]
Would you mind elaborating on the issue?

It's my understanding that when time-based loss happens, bytes-in-flight gets reduced because we declare at least one packet to be lost. Doesn't that open window that we can use for sending something?

**Comment by janaiyengar** [comment]
Yes, that is correct, but commonly, the window reduction is substantially larger than the reduction in bytes-in-flight. This results in inflight > cwnd until a number of acks are received, and the retransmission waits to until these acks are received.

The ideal solution here is to implement PRR (https://tools.ietf.org/html/rfc6937), or to use pacing. A simple solution is to allow one retransmission to be sent so that in the common case of one packet loss, the receiver can deliver stream data.

Does that make sense?

**Comment by kazuho** [comment]
Thank you for elaborating. Makes sense.
