### ISSUE TITLE
Stateless reset detection

### ISSUE THREAD

**Issue by sknat** [h2o/quicly#146]
There seems to be an issue in the `is_stateless_reset` function.

* Offset calculation seems to be wrong per [https://tools.ietf.org/html/draft-ietf-quic-transport-19#page-53](https://tools.ietf.org/html/draft-ietf-quic-transport-19#page-53)
* In the server case `conn->super.peer.stateless_reset_token` can be uninitialized as the client can only specify it via a NEW_CONNECTION_ID frame which isn't always sent. So in the unfortunate case of receiving a packet zeroed from byte 16 through 39, it will be detected as a reset.

**Comment by kazuho** [comment]
> Offset calculation seems to be wrong per https://tools.ietf.org/html/draft-ietf-quic-transport-19#page-53

How is it wrong? My understanding is that I-D states that the reset token is the last 16 bytes of the QUIC packet, and that we are doing that correctly.

> So in the unfortunate case of receiving a packet zeroed from byte 16 through 39, it will be detected as a reset.

This is a non-issue. The design of stateless reset is based on the fact that a 128-bit random number would never collide in practice. Using one of the values for special case is a non-issue.

**Comment by sknat** [comment]
You're right on point (1) my bad, I misread the documentation, it's effectively the last 16 bytes that are used for the token. So my patch doesn't apply :/

The weird behavior that lead me to that is we receive a 1280 bytes long decoded packet ending with zeroes. But that might be due to a an error on our use of quicly.

Thanks for your reply anyway !
