### ISSUE TITLE
retain quicly_acks_t for some time after RTO

### ISSUE THREAD

**Issue by kazuho** [h2o/quicly#15]
Even after RTO timer fires for a particular PN, we still need to keep quicly_ack_t for that PN for some more time, because it could be due to the ACK being lost. In such case, the peer will retransmit the ACK and we need to reflect that.

**Comment by janaiyengar** [comment]
... or the path RTT could have changed. In general for all types of retransmissions, it's useful to keep one previous transmission, since a late ack for a packet should cause subsequent retransmissions to be aborted.

**Comment by kazuho** [comment]
tentatively done in 30ffe50.

**Comment by kazuho** [comment]
ToDo: figure out the correct duration, like 4 * (srtt + max_delay)?

**Comment by janaiyengar** [comment]
The model I have in mind is slightly different, so I'd like to run it by you. I want 1 or 2 transmissions of a packet in the map at any given time: 1 when it's the first transmission, and 2 after that. Any time there's a retransmission, you remove the packet that is two transmissions in the past. Does this make sense? This would avoid any asynchronous removals, which seems iffy to me.

**Comment by kazuho** [comment]
I am not sure if that model works in QUIC, because there is no "retransmission" of a packet.

For every transmission, we gather frames from the pending data (i.e. pending means things that need to be transmitted but that are not inflight). When a packet is deemed as lost, we update the states of data being referred to from the inflight map to the pending state (unless it has been already acknowledged by another packet).

Or am I misreading your comment?

**Comment by janaiyengar** [comment]
Apologies for the delay. I'll retract my suggestion -- you are right. I think that a simple timer is the right approach, but we could also do an epoch based one that might scale better. Meaning that when a packet sent after a packet is marked as lost is acked, then the lost packet is removed from the map. For instance:
t0: Packet with PN 15  marked as lost.
t1: New packets sent (with PN 25, 26, ...).
t2: Ack received for PN >= 25 or RTO timer fires. Remove PN 15 from map.
(Any time ack for PN 15 is received, it also causes PN 15 to be removed from the map.)

This gives you one packet RTT worth of time but avoids having to use a new timer.

**Comment by kazuho** [comment]
Closed by #13.
