### ISSUE TITLE
Make ACK_DELAY_EXPONENT a config variable

### ISSUE THREAD

**Issue by janaiyengar** [h2o/quicly#167]
This is right now a constant, but it should be configurable based on the deployment, I think. For instance, a value of 10 makes sense for the public internet, but it might not be for a DC-like environment.

**Comment by kazuho** [comment]
It is a fixed value based on the design being that granularity of the `now` callback is milliseconds. At the moment, we cannot report anything in sub-millisecond order, and therefore ACK_DELAY_EXPONENT below 10 does not make sense.

I'm happy to support microsecond granularity, however it would require some effort, considering that we need to change h2o as well (h2o's time granularity is also milliseconds at the moment).

**Comment by janaiyengar** [comment]
Yeah, good point. I don't think we need this yet. We might need it later,
but that can be a separate effort. I'll close this issue.
