### ISSUE TITLE
timer related crash in H2O

### ISSUE THREAD

**Issue by kazuho** [h2o/quicly#171]
After the adoption of #158, we are seeing frequent assertion failures in the kazuho/quic branch of H2O.

It seems that the assertion failure is happening due to the following behavior:
* server accepts a new connection, send Initial and two Handshake packets
* server receives an ACK for the first Handshake packet it has sent (interestingly, the ACK does not seem to include an acknowledgement for the second Handshake packet)
  * loss timer is set for the Initial packet
  * initial space is discarded, but the loss timer remains active<sup>1</sup>
* loss timer fires, and quicly_send is being called
  * but because it's not a PTO, nothing is newly marked as being lost
  * therefore, we have nothing to transmit
  * SPTO timer is activated, pointing to a time in the past<sup>2</sup>
  * timer is adjusted to the current time (the intent is of the adjustment logic is to not let functions *other than* quicly_send specify a time in the past)
  * assertion failure is invoked at the end of quicly_send function, because quicly_send is never expected to set a timer pointing to past or current time, because it's a sign of infinite loop<sup>3</sup>

We can certainly fix 1, by adjusting the loss timer to be updated when the Initial space is discarded. However, that would not fix the issue, because the same thing can happen within 1-RTT space, for example when the loss timer fires but the packet that triggered the loss timer contained a stream that has since been cancelled. In such case, quicly_send would have nothing to send.

2 seems to be an issue. I think we'd better be sending SPTOs even when loss timer is active. Not sure how important that is though.

We can fix 3, by letting quicly_send function tail-recurse when the timer is set to the current time. We can limit the number of tail recursions to avoid infinite loop.

**Comment by kazuho** [comment]
To reproduce: checkout f4491c0 of h2o (current head of kazuho/quic branch), and run `make -f misc/docker-ci/check.mk fuzz`. t/40http3.t fails at certain rate. You can log on to the docker image for faster reproduction.

**Comment by kazuho** [comment]
> We can certainly fix 1, by adjusting the loss timer to be updated when the Initial space is discarded. 

Kazuho will fix this. The change would be to discard the Initial space (and the entries in sentmap) before processing the first Handshake packet. Then, loss timer for the Initial packet would no longer be activated by a Handshake packet.

> 2 seems to be an issue. I think we'd better be sending SPTOs even when loss timer is active. Not sure how important that is though.

We agree that the spec. should be kept as-is for fairness with TCP, even though we acknowledge the fact that PTO is sometimes more aggressive than time-threshold loss detection (due to ignoring rttvar).

> We can fix 3, by letting quicly_send function tail-recurse when the timer is set to the current time. We can limit the number of tail recursions to avoid infinite loop.

Kazuho will implement this. The maximum number of tail recursion should be set to zero.

**Comment by janaiyengar** [comment]
That sounds good to me, thanks Kazuho!

**Comment by kazuho** [comment]
> What to do with SPTO?

We agreed that we do not need to care, considering SPTO to be an optimization (that sometimes help).
