### ISSUE TITLE
inline code in headers should be compilable from a C++ program

### ISSUE THREAD

**Issue by Overcow** [h2o/quicly#176]
The branch **origin/kazuho/streambuf-pullvec** updated **streambuf.h** with the following inline functions:

```
inline void quicly_streambuf_egress_shift(quicly_stream_t *stream, size_t delta)
inline int quicly_streambuf_egress_write(quicly_stream_t *stream, const void *src, size_t len)
inline int quicly_streambuf_egress_write_vec(quicly_stream_t *stream, quicly_sendbuf_vec_t *vec)
inline void quicly_streambuf_ingress_shift(quicly_stream_t *stream, size_t delta)
inline ptls_iovec_t quicly_streambuf_ingress_get(quicly_stream_t *stream)
```

In the header, each function assigns a quickly_streambut_t*
Eg. 
`quicly_streambuf_t *sbuf = stream->data;`

This will not compile in C++ programs that include the header since C++ will not automatically cast void* to quicly_streambuf_t*. In order to support C++ applications we will need to cast these assignments.

Eg.
`quicly_streambuf_t *sbuf = (quicly_streambuf_t*)stream->data;`

**Comment by kazuho** [comment]
That's definitely true.

I think I've fixed the issues in the commit above (that has gone directly into master). Please feel free to file a PR that addresses the issues if there's something remaining.

**Comment by Overcow** [comment]
Thank you - much appreciated. I will provide a PR if I see any other issue(s).
