### ISSUE TITLE
Cap the number of gaps in lists that might contain gaps

### ISSUE THREAD

**Issue by kazuho** [h2o/quicly#216]
The lists being:
* sentmap
* `quicly_ranges_t` - used for stream-level received range list (`quicly_recvstate_t::received`), etc.

Quicly should log and close connection when the number of gaps reaches the threshold.

**Comment by kazuho** [comment]
Below are the objects that might contain unbounded number of gaps, the severity, and the action that should be taken when the number of gaps becomes greater than the thresholds. Each object should have their (possibly) hard-coded thresholds.

|object|action|severity|
|:---:|:---:|:---:|
|quicly_pnspace_t::ack_queue|drop old ones<sup>1</sup>|high|
|quicly_recvstate_t::received|close the connection|high|
|quicly_sendstate_t::acked|drop ones with larger offsets|low|
|quicly_conn_t::egress.sentmap|drop old ones|deferred|
|quicly_sendstate_t::pending|- (capped by the limits of `quicly_sendstate_t::acked`)|-|

1: Should also send PING, when the number of gaps reaches a different threshold that is smaller than the threshold that causes old ranges to be dropped.

**Comment by kazuho** [comment]
@janaiyengar Does the table look correct to you?

**Comment by janaiyengar** [comment]
A few clarifications:
- Did you mean to add `quicly_recvstate_t::recvstate` instead of `quicly_recvstate_t::received`?
- Did you mean `quicly_sendstate_t::sendstate` instead of `quicly_sendstate_t::acked`?
- On `egress.sentmap`, the old ones are still unacked outstanding packets, right? If so, dropping them doesn't make sense. I _think_ this should cause the connection to close.
- Which one is `pending`?
- How are you determining the severity?

**Comment by kazuho** [comment]
> * Did you mean to add `quicly_recvstate_t::recvstate` instead of `quicly_recvstate_t::received`?
> * Did you mean `quicly_sendstate_t::sendstate` instead of `quicly_sendstate_t::acked`?
> * Which one is `pending`?

I meant the ones I stated. `received` which is a member of `quicly_recvstate_t`, and `acked`, `pending` which are nembers of `quicly_sendstate_t`. I used `type::member` notation of C++.

> * On `egress.sentmap`, the old ones are still unacked outstanding packets, right? If so, dropping them doesn't make sense. I *think* this should cause the connection to close.

Yes, they are unacked outstanding packets, and I am not sure if dropping them doesn't make sense. Would you mind elaborating?

We drop information of unacked outstanding packets after 3 PTO. That can sometimes happen earlier than that. Though, ... (see below).

> How are you determining the severity?

The ones that are easy to trigger are marked "high."

Attack on `quicly_sendstate__t::acked` is marked `low`, because the attack is much more difficult, due to the fact that how the STREAM frames are sent is controlled by us. The attack vector is by choosing what to ack (rather than just sending something).

Attack on `quicly_conn_t::egress.sentmap` is marked `deferred`, as I am not sure if there is a security concern here, because it is my understanding that the number of packets being sent within every RTT will be reduced when there is a potential loss.

**Comment by kazuho** [comment]
Discussed with @janaiyengar, and agreed to do the following.

We will have two watermarks for the number of ranges in `quicly_pn_space::ack_queue`. When we hit the low watermark, we'd send ACK+PING (maybe periodically). When we hit the high watermark, we'd drop incoming packets, while sending ACK+PING (where that ACK carries the PNs that have been received prior to the dropped packet). For `quicly_recvstate_t::received`, `quicly_sendstate_t::acked`, `quicly_sendstate_t::pending`, we would have hard-coded limits. We will close the connection when the number of ranges exceed those limits.

The intention is to limit the state we maintain at the cost of reducing speed when we hit an extraordinary condition. We would also log such conditions, so that we can see if we are actually hitting them.

Finally, we agreed that we do not need a limit for the number of entries in `quicly_conn_t::egress.sentmap`, as the addition to the sentmap is controlled by us. Rather, we need a defense against an optimistic ACK attack, for which we would skip every one packet number out of 256 packets we send. We'd register that packet number into the sentmap so that we can detect an attacker and close the connection.
