### ISSUE TITLE
throughput issue

### ISSUE THREAD

**Issue by Winters123** [h2o/quicly#232]
Hi,

There is a problem that confuses me a lot. I used to servers to test `quicly` with the 10G connection (tested by `iperf` and it works fine). But when I use `-p` parameter in `quicly` to send a data block from one server to another, I found the total throughput was always between 250Mbps-350Mbps. Any hint on what caused the low throughput? 

Thanks in advance.

**Comment by kazuho** [comment]
Sorry for the late reply. I think you are getting maximum performance at the moment. I'd assume that either side is consuming 100% CPU time?
