### ISSUE TITLE
Assert fails when len=0 & wrote_all=1 in on_send_emit 

### ISSUE THREAD

**Issue by sknat** [h2o/quicly#233]
Hi quicly team,

I'm hitting an assert at `sendstate.c:166` following a `on_send_emit` callback, where `len == 0` and `wrote_all == 1`.
This `assert(state->acked.ranges[0].end <= state->pending.ranges[0].start);` seems to happen because we don't have anymore pending ranges (`numranges == 0`)

It's a quite weird corner case, which happens only with 10k+ streams. I have a workaround that makes the sentmap allocation conditional to `len > 0` in `quicly_send_stream` but this fails to cleanup streams correctly at teardown and doesn't really seem ideal to me. 

I'm under the impression that this could be solved in the scheduling & the egress_emit/shift api : the `on_send_emit` maybe shouldn't be called if no data is pending, but I'm not really clear what the correct way to do this is and what the assumptions behind egress_emit / egress_shift are.

Any thoughts ?

**Comment by sknat** [comment]
After further investigation, this bug seems to be caused by a race condition in our code that schedules streams with no data to send.

But I think the issue still remains valid from an API user standpoint
* Either `on_send_emit` should fail when `len == 0` is returned
* Or `quicly_send_stream` shouldn't update the sentmap with args that break the assert

**Comment by kazuho** [comment]
> * Either `on_send_emit` should fail when `len == 0` is returned

I think that this is the hidden contract. Would you mind adding the assertion, confirm that it does not break something?

**Comment by sknat** [comment]
Thanks ! Added the assert and updated the comment.
