### ISSUE TITLE
Expose next expected packet number

### ISSUE THREAD

**Issue by MathiasRaoul** [h2o/quicly#245]
As discussed in #225 , to properly offload packets decryption it could be great to have access to next_expected_pn (used to determine the packet number). 

We did this in vpp : https://github.com/vpp-quic/quicly/tree/next_expected_pn

Our offloading implementation  in quic vpp plugin is here : https://gerrit.fd.io/r/c/vpp/+/23538

**Comment by kazuho** [comment]
Sorry for not responding. #264 looks great as a fix, I have merged it.
