### ISSUE TITLE
Multiple UDP sockets

### ISSUE THREAD

**Issue by bulbaasd24** [h2o/quicly#358]
Can multiple UDP sockets use same quicly_context_t ctx ? This is in reference to the example-echo program.

**Comment by kazuho** [comment]
When `quicly_context_t::cid_encryptor` is set to a non-NULL value, Connection IDs are used to distinguish between the connections using one UDP port.

src/cli.c might be a good place to see how it can be used.

**Comment by bulbaasd24** [comment]
Thanks Kazuko. That helped.
