### ISSUE TITLE
Adding supplementary congestion control algorithms

### ISSUE THREAD

**Issue by TheJokr** [h2o/quicly#365]
I recently added the [CUBIC CC algorithm](https://tools.ietf.org/html/rfc8312) to an older quicly version for a project. We have since verified that it works as expected and would be happy to contribute the code back to quicly. But we figured it would be a good idea to discuss the topic in an issue first before porting the changes to quicly's master and submitting a PR. To allow applications to select between CC algorithms, a few changes to the CC interface are necessary:

1) `quicly_context_t` is amended with a new struct `quicly_cc_conf_t` to pass the desired algorithm (similar to the parameters for [loss.h](https://github.com/h2o/quicly/blob/0ab1c6723ce308538a1313382e3e3475cd6b7b36/include/quicly/loss.h#L34-L69)). This struct could also be extended to configure the algorithm, e.g., the beta and C parameters in CUBIC.

2) `quicly_cc_t` gains two new members: a pointer to a struct that represents a CC algorithm (i.e., containing pointers to the implementation of the `quicly_cc_init`, `quicly_cc_on_acked`, `quicly_cc_on_lost`, and `quicly_cc_on_persistent_congestion` functions) and a union to store algorithm-specific state (e.g., K and W_max for CUBIC)

3) New `quicly_cc_*` functions replace the ones in `cc-reno.c` to forward calls to the function pointers described above. Ideally, since different algorithms require different information about the connection, these would also be passed a (const) pointer to `quicly_conn_t`. For example, CUBIC requires the smoothed RTT estimate which is not available without pointer hacks in the interface the Reno implementation uses.

4) The old functions in `cc-reno.c` are renamed (e.g., to `quicly_reno_*`) and make up the struct for the Reno CC implementation (which continues to be the default algorithm).

I think this interface allows for the greatest flexibility going forward without any changes outside of the files implementing congestion control (other than the new context entry). I'm very interested to hear your feedback and improvements for this proposal, and whether you are interested in pursuing additional/modular congestion control algorithms at all.

PS: We also looked at implementing Google's [BBR algorithm](https://github.com/google/bbr) for our project, but that requires pacing. As far as we could tell, quicly does not support that. Are there plans to do so in the future, considering that [the spec recommends it](https://tools.ietf.org/html/draft-ietf-quic-recovery-29#section-7.9)?

**Comment by janaiyengar** [comment]
Thank you, @TheJokr -- this sounds like an excellent contribution! On the pacing question: Yes, we are planning to implement it. We might need to modify the CC interface to handle that when we do. (I'd like to hear @kazuho's comments as well.)

**Comment by kazuho** [comment]
This is exciting! Thank you @TheJokr.

The API being described sounds fine. I am looking forward to seeing the pull request 😍

**Comment by TheJokr** [comment]
Awesome - I'll get right to work on porting it then 👍
