### ISSUE TITLE
QUIC version

### ISSUE THREAD

**Issue by Shawnxm** [h2o/quicly#481]
Is there any way that I could check the QUIC version (e.g., Google QUIC, IEFT QUIC) used, or it was just a separately implemented QUIC?

**Comment by chenbd** [comment]
quic is standardized by ietf in [rfc9000](https://www.rfc-editor.org/rfc/rfc9000.html).
most implementation(including quicly) should conform to IMO.

**Comment by kazuho** [comment]
At the moment, quicly supports three versions of IETF QUIC: version 1, draft-29, draft-27. See https://github.com/h2o/quicly/blob/master/lib/quicly.c#L6394-L6395.

We will eventually drop support for the draft versions.
