### ISSUE TITLE
BUG: Receipt of NEW_TOKEN by a server is not handled correctly

### ISSUE THREAD

**Issue by bathooman** [h2o/quicly#525]
### Description
- Type: Non-conformance Bug
- Priority: Medium

---------------------------------------------------------------
## Non-conformance Bug
Commit: 482610bf84af287648c42c0cc0e3429915421979

**Expected behavior**   
The QUIC 1 [RFC](https://www.rfc-editor.org/rfc/rfc9000.html) in section 19.7 states that:

> Clients MUST NOT send NEW_TOKEN frames. A server MUST treat receipt of a NEW_TOKEN frame as a connection error of type PROTOCOL_VIOLATION.

**Actual behavior** 
When a client and a server are exchanging packets, receipt of a NEW_TOKEN frame will not trigger any type of error by the server. In the following, the server is running on port 8462, and the client is running on port 36417. As one can see, when the server receives an NT, it does not generate any error and acknowledges the packet containing the NT later:

![image](https://user-images.githubusercontent.com/3464382/184657915-e4a9bc45-9b03-4034-b5dd-440315df92fb.png)

-------------------------

![image](https://user-images.githubusercontent.com/3464382/184659220-074c2f39-5bb2-43ff-9ce8-e69b1488087b.png)

I have attached the captured interaction between a QUIC client and a server containing the mentioned problem. The master secret log file is also attached so that one can decrypt the exchanged traffic.

[client-generated-token-bug.zip](https://github.com/h2o/quicly/files/9337925/client-generated-token-bug.zip)

**Comment by kazuho** [comment]
Thank you for reporting the issue.

Your report is very easy to understand and full of details to diagnose. Thank you very much.

I acknowledge that we have a bug here.

**Comment by homyhost** [comment]
Hello,

Is there any effort to fix the bug?

**Comment by kazuho** [comment]
Thank you for the nudge! Fixed.
