### ISSUE TITLE
install on OSX

### ISSUE THREAD

**Issue by marten-seemann** [h2o/quicly#81]
This issue is most definitely an issue with my limited C knowledge, so I'm apologizing in advance for this newbie question.

I'm getting the following error when trying to build quicly:
```
[ 37%] Built target quicly
Scanning dependencies of target cli
[ 40%] Building C object CMakeFiles/cli.dir/deps/picotls/lib/openssl.c.o
[ 43%] Building C object CMakeFiles/cli.dir/deps/picotls/lib/pembase64.c.o
[ 46%] Building C object CMakeFiles/cli.dir/deps/picotls/lib/picotls.c.o
[ 50%] Building C object CMakeFiles/cli.dir/src/cli.c.o
[ 53%] Linking C executable cli
Undefined symbols for architecture x86_64:
  "_X509_check_host", referenced from:
      _verify_cert in openssl.c.o
  "_X509_check_ip_asc", referenced from:
      _verify_cert in openssl.c.o
ld: symbol(s) not found for architecture x86_64
```

I installed OpenSSL using Homebrew and set the symlinks according to this article: https://medium.com/@timmykko/using-openssl-library-with-macos-sierra-7807cfd47892

**Comment by marten-seemann** [comment]
I figured it out:
```bash
export PKG_CONFIG_PATH="/usr/local/opt/openssl/lib/pkgconfig"
```

**Comment by so2boy** [comment]
same problem as yours, but the "export xxx" does not work!

**Comment by so2boy** [comment]
I solved it by:

PKG_CONFIG_PATH="/usr/local/opt/openssl/lib/pkgconfig" cmake . -DOPENSSL_CRYPTO_LIBRARY=/usr/local/Cellar/openssl/1.0.2s/lib/libcrypto.dylib -DOPENSSL_SSL_LIBRARY=/usr/local/Cellar/openssl/1.0.2s/lib/libssl.dylib
